export const SelectRecordLimit = [
  { id: 5, value: "5" },
  { id: 10, value: "10" },

  { id: 30, value: "30" },
  { id: 40, value: "40" },
  { id: 50, value: "50" },
];

export const SelectGender = [
  { id: "Male", value: "Male" },
  { id: "Female", value: "Female" },
  { id: "Other", value: "Other" },
];

export const UserDemoData = [
  {
    id: 1,
    name: "Leanne Graham",
    username: "Bret",
    email: "Sincere@april.biz",
    address: {
      street: "Kulas Light",
      suite: "Apt. 556",
      city: "Gwenborough",
      zipcode: "92998-3874",
      geo: {
        lat: "-37.3159",
        lng: "81.1496",
      },
    },
    phone: "1-770-736-8031 x56442",
    website: "hildegard.org",
    company: {
      name: "Romaguera-Crona",
      catchPhrase: "Multi-layered client-server neural-net",
      bs: "harness real-time e-markets",
    },
  },
  {
    id: 2,
    name: "Ervin Howell",
    username: "Antonette",
    email: "Shanna@melissa.tv",
    address: {
      street: "Victor Plains",
      suite: "Suite 879",
      city: "Wisokyburgh",
      zipcode: "90566-7771",
      geo: {
        lat: "-43.9509",
        lng: "-34.4618",
      },
    },
    phone: "010-692-6593 x09125",
    website: "anastasia.net",
    company: {
      name: "Deckow-Crist",
      catchPhrase: "Proactive didactic contingency",
      bs: "synergize scalable supply-chains",
    },
  },
  {
    id: 3,
    name: "Clementine Bauch",
    username: "Samantha",
    email: "Nathan@yesenia.net",
    address: {
      street: "Douglas Extension",
      suite: "Suite 847",
      city: "McKenziehaven",
      zipcode: "59590-4157",
      geo: {
        lat: "-68.6102",
        lng: "-47.0653",
      },
    },
    phone: "1-463-123-4447",
    website: "ramiro.info",
    company: {
      name: "Romaguera-Jacobson",
      catchPhrase: "Face to face bifurcated interface",
      bs: "e-enable strategic applications",
    },
  },
  {
    id: 4,
    name: "Patricia Lebsack",
    username: "Karianne",
    email: "Julianne.OConner@kory.org",
    address: {
      street: "Hoeger Mall",
      suite: "Apt. 692",
      city: "South Elvis",
      zipcode: "53919-4257",
      geo: {
        lat: "29.4572",
        lng: "-164.2990",
      },
    },
    phone: "493-170-9623 x156",
    website: "kale.biz",
    company: {
      name: "Robel-Corkery",
      catchPhrase: "Multi-tiered zero tolerance productivity",
      bs: "transition cutting-edge web services",
    },
  },
  {
    id: 5,
    name: "Chelsey Dietrich",
    username: "Kamren",
    email: "Lucio_Hettinger@annie.ca",
    address: {
      street: "Skiles Walks",
      suite: "Suite 351",
      city: "Roscoeview",
      zipcode: "33263",
      geo: {
        lat: "-31.8129",
        lng: "62.5342",
      },
    },
    phone: "(254)954-1289",
    website: "demarco.info",
    company: {
      name: "Keebler LLC",
      catchPhrase: "User-centric fault-tolerant solution",
      bs: "revolutionize end-to-end systems",
    },
  },
  {
    id: 6,
    name: "Mrs. Dennis Schulist",
    username: "Leopoldo_Corkery",
    email: "Karley_Dach@jasper.info",
    address: {
      street: "Norberto Crossing",
      suite: "Apt. 950",
      city: "South Christy",
      zipcode: "23505-1337",
      geo: {
        lat: "-71.4197",
        lng: "71.7478",
      },
    },
    phone: "1-477-935-8478 x6430",
    website: "ola.org",
    company: {
      name: "Considine-Lockman",
      catchPhrase: "Synchronised bottom-line interface",
      bs: "e-enable innovative applications",
    },
  },
  {
    id: 7,
    name: "Kurtis Weissnat",
    username: "Elwyn.Skiles",
    email: "Telly.Hoeger@billy.biz",
    address: {
      street: "Rex Trail",
      suite: "Suite 280",
      city: "Howemouth",
      zipcode: "58804-1099",
      geo: {
        lat: "24.8918",
        lng: "21.8984",
      },
    },
    phone: "210.067.6132",
    website: "elvis.io",
    company: {
      name: "Johns Group",
      catchPhrase: "Configurable multimedia task-force",
      bs: "generate enterprise e-tailers",
    },
  },
  {
    id: 8,
    name: "Nicholas Runolfsdottir V",
    username: "Maxime_Nienow",
    email: "Sherwood@rosamond.me",
    address: {
      street: "Ellsworth Summit",
      suite: "Suite 729",
      city: "Aliyaview",
      zipcode: "45169",
      geo: {
        lat: "-14.3990",
        lng: "-120.7677",
      },
    },
    phone: "586.493.6943 x140",
    website: "jacynthe.com",
    company: {
      name: "Abernathy Group",
      catchPhrase: "Implemented secondary concept",
      bs: "e-enable extensible e-tailers",
    },
  },
  {
    id: 9,
    name: "Glenna Reichert",
    username: "Delphine",
    email: "Chaim_McDermott@dana.io",
    address: {
      street: "Dayna Park",
      suite: "Suite 449",
      city: "Bartholomebury",
      zipcode: "76495-3109",
      geo: {
        lat: "24.6463",
        lng: "-168.8889",
      },
    },
    phone: "(775)976-6794 x41206",
    website: "conrad.com",
    company: {
      name: "Yost and Sons",
      catchPhrase: "Switchable contextually-based project",
      bs: "aggregate real-time technologies",
    },
  },
  {
    id: 10,
    name: "Clementina DuBuque",
    username: "Moriah.Stanton",
    email: "Rey.Padberg@karina.biz",
    address: {
      street: "Kattie Turnpike",
      suite: "Suite 198",
      city: "Lebsackbury",
      zipcode: "31428-2261",
      geo: {
        lat: "-38.2386",
        lng: "57.2232",
      },
    },
    phone: "024-648-3804",
    website: "ambrose.net",
    company: {
      name: "Hoeger LLC",
      catchPhrase: "Centralized empowering task-force",
      bs: "target end-to-end models",
    },
  },
];
export const barberDetail = {
  salon_id: 1,
  salon_name: "Hens",
  salon_email: "sharmahemangi760@gmail.com",
  salon_password: "827ccb0eea8a706c4c34a16891f84e7b",
  salon_hours_rate: 20,
  salon_address: "Newyork ",
  salon_zipcode: "0380061",
  salon_profile: "1595415168856_images-(3).jpeg",
  salon_device_id: "49991959e39321ab",
  salon_device_type: "android",
  salon_fcm_id:
    "dq3N6e-iR7CDACwoHKN8yC:APA91bHo8ko9OkeO4bEpGCPRoI7f8YAT3jxDpAOPW4UpENpK-_ObLmyTaaglBxtd0En7rH1rvb2fc1U3InH4SGpIyT0PbFIpk9Bm-dAJdT6p9EPvPJfWtmO7KsIY-o4CLyilDqPFy18-",
  salon_token: 36105,
  salon_gallery_image1: ["1595315847862_images-(3).jpeg"],
  rating: 0.8,
  salon_about: "Nice",
  salon_status: 1,
  salon_available_time: null,
  // [
  //   { start_time: "10 am", day: "Sunday", end_time: "10 pm", select: true },
  //   { start_time: "10 am", day: "Monday", end_time: "10 pm", select: true },
  //   {
  //     start_time: "10 am",
  //     day: "Tuesday",
  //     end_time: "10 pm",
  //     select: true,
  //   },
  //   {
  //     start_time: "10 am",
  //     day: "Wednesday",
  //     end_time: "10 pm",
  //     select: true,
  //   },
  //   {
  //     start_time: "10 am",
  //     day: "Thursday",
  //     end_time: "10 pm",
  //     select: true,
  //   },
  //   { start_time: "10 am", day: "Friday", end_time: "10 pm", select: true },
  //   {
  //     start_time: "Closed",
  //     day: "Saturday",
  //     end_time: "Closed",
  //     select: false,
  //   },
  // ],
  service: [
    {
      service_id: 5,
      salon_service_name: "Hair cut",
      salon_service_image: "haircut.png",
      salon_service_status: 1,
      status: 1,
    },
    {
      service_id: 6,
      salon_service_name: "Hair Color",
      salon_service_image: "hairColor.png",
      salon_service_status: 1,
      status: 1,
    },
  ],
  business_status: 1,
  created_at: "2020-07-23T00:00:00.000Z",
};

export const barberTimeData = [
  {
    id: 0,
    start_time: "10 am",
    day: "Sunday",
    end_time: "10 am",
    select: false,
  },
  {
    id: 1,
    start_time: "10 am",
    day: "Monday",
    end_time: "10 pm",
    select: false,
  },
  {
    id: 2,
    start_time: "10 am",
    day: "Tuesday",
    end_time: "10 pm",
    select: false,
  },
  {
    id: 3,
    start_time: "10 am",
    day: "Wednesday",
    end_time: "10 pm",
    select: false,
  },
  {
    id: 4,
    start_time: "10 am",
    day: "Thursday",
    end_time: "10 pm",
    select: false,
  },
  {
    id: 5,
    start_time: "10 am",
    day: "Friday",
    end_time: "10 pm",
    select: false,
  },
  {
    id: 6,
    start_time: "10 am",
    day: "Saturday",
    end_time: "10 am",
    select: false,
  },
];

export const UserData = [
  {
    id: 1,
    name: "Liam",
    email: "Liam@gmail.com",
    images: "./assets/images/users/user-2.jpg",
    pincode: "869547",
    active: true,
    bookings: "true",
    bookings_Details: "yes",
  },
  {
    id: 2,
    name: "Noah",
    email: "Noah@gmail.com",
    images: "./assets/images/users/user-2.jpg",
    pincode: "869547",
    active: true,
    bookings: "true",
    bookings_Details: "yes",
  },
  {
    id: 3,
    name: "William",
    email: "William@gmail.com",
    images: "./assets/images/users/user-2.jpg",
    pincode: "869547",
    active: true,
    bookings: "true",
    bookings_Details: "yes",
  },
  {
    id: 4,
    name: "James",
    email: "James@gmail.com",
    images: "./assets/images/users/user-2.jpg",
    pincode: "869547",
    active: true,
    bookings: "true",
    bookings_Details: "yes",
  },
  {
    id: 5,
    name: "Oliver",
    email: "Oliver@gmail.com",
    images: "./assets/images/users/user-2.jpg",
    pincode: "869547",
    active: true,
    bookings: "true",
    bookings_Details: "yes",
  },
  {
    id: 6,
    name: "Benjamin",
    email: "Benjamin@gmail.com",
    images: "./assets/images/users/user-2.jpg",
    pincode: "869547",
    active: true,
    bookings: "true",
    bookings_Details: "yes",
  },
  {
    id: 7,
    name: "Elijah",
    email: "Elijah@gmail.com",
    images: "./assets/images/users/user-2.jpg",
    pincode: "869547",
    active: true,
    bookings: "true",
    bookings_Details: "yes",
  },
  {
    id: 8,
    name: "Lucas",
    email: "Lucas@gmail.com",
    images: "./assets/images/users/user-2.jpg",
    pincode: "869547",
    active: true,
    bookings: "true",
    bookings_Details: "yes",
  },
  {
    id: 9,
    name: "Mason",
    email: "Mason@gmail.com",
    images: "./assets/images/users/user-2.jpg",
    pincode: "869547",
    active: true,
    bookings: "true",
    bookings_Details: "yes",
  },
  {
    id: 10,
    name: "Logan",
    email: "Logan@gmail.com",
    images: "./assets/images/users/user-2.jpg",
    pincode: "869547",
    active: true,
    bookings: "true",
    bookings_Details: "yes",
  },
  {
    id: 11,
    name: "Emma",
    email: "Emma@gmail.com",
    images: "./assets/images/users/user-2.jpg",
    pincode: "869547",
    active: true,
    bookings: "true",
    bookings_Details: "yes",
  },
  {
    id: 12,
    name: "Sophia",
    email: "Sophia@gmail.com",
    images: "./assets/images/users/user-2.jpg",
    pincode: "869547",
    active: true,
    bookings: "true",
    bookings_Details: "yes",
  },
  {
    id: 13,
    name: "Amelia",
    email: "Amelia@gmail.com",
    images: "./assets/images/users/user-2.jpg",
    pincode: "869547",
    active: true,
    bookings: "true",
    bookings_Details: "yes",
  },
];

export const BarberData = [
  {
    id: 1,
    name: "Liam",
    description: "Liam@gmail.com",
    pincode: "869547",
    images: "./assets/images/users/user-1.jpg",
    services: "true",
    opening_hours: "yes",
  },
  {
    id: 2,
    name: "Noah",
    description: "Noah@gmail.com",
    pincode: "869547",
    images: "./assets/images/users/user-2.jpg",
    services: "true",
    opening_hours: "yes",
  },
  {
    id: 3,
    name: "William",
    description: "William@gmail.com",
    pincode: "869547",
    images: "./assets/images/users/user-3.jpg",
    services: "true",
    opening_hours: "yes",
  },
  {
    id: 4,
    name: "James",
    description: "James@gmail.com",
    pincode: "869547",
    images: "./assets/images/users/user-4.jpg",
    services: "true",
    opening_hours: "yes",
  },
  {
    id: 5,
    name: "Oliver",
    description: "Oliver@gmail.com",
    pincode: "869547",
    images: "./assets/images/users/user-5.jpg",
    services: "true",
    opening_hours: "yes",
  },
  {
    id: 6,
    name: "Benjamin",
    description: "Benjamin@gmail.com",
    pincode: "869547",
    images: "./assets/images/users/user-6.jpg",
    services: "true",
    opening_hours: "yes",
  },
  {
    id: 7,
    name: "Elijah",
    description: "Elijah@gmail.com",
    pincode: "869547",
    images: "./assets/images/users/user-3.jpg",
    services: "true",
    opening_hours: "yes",
  },
  {
    id: 8,
    name: "Lucas",
    description: "Lucas@gmail.com",
    pincode: "869547",
    images: "./assets/images/users/user-2.jpg",
    services: "true",
    opening_hours: "yes",
  },
  {
    id: 9,
    name: "Mason",
    description: "Mason@gmail.com",
    pincode: "869547",
    images: "./assets/images/users/user-4.jpg",
    services: "true",
    opening_hours: "yes",
  },
  {
    id: 10,
    name: "Logan",
    description: "Logan@gmail.com",
    pincode: "869547",
    images: "./assets/images/users/user-1.jpg",
    services: "true",
    opening_hours: "yes",
  },
  {
    id: 11,
    name: "Emma",
    description: "Emma@gmail.com",
    pincode: "869547",
    images: "./assets/images/users/user-5.jpg",
    services: "true",
    opening_hours: "yes",
  },
  {
    id: 12,
    name: "Sophia",
    description: "Sophia@gmail.com",
    pincode: "869547",
    images: "./assets/images/users/user-6.jpg",
    services: "true",
    opening_hours: "yes",
  },
  {
    id: 13,
    name: "Amelia",
    description: "Amelia@gmail.com",
    pincode: "869547",
    images: "./assets/images/users/user-1.jpg",
    services: "true",
    opening_hours: "yes",
  },
];

export const Service = [
  {
    id: 1,
    name: "hair color",
    images: "./assets/images/Services/hair-color.png",
    services: "true",
    opening_hours: "yes",
  },
  {
    id: 2,
    name: "hair-cut",
    images: "./assets/images/Services/hair-cut.png",
    services: "true",
    opening_hours: "yes",
  },
  {
    id: 3,
    name: "hair style",
    images: "./assets/images/Services/hair-style.png",
    services: "true",
    opening_hours: "yes",
  },
  {
    id: 4,
    name: "mekup",
    images: "./assets/images/Services/mekup.png",
    services: "true",
    opening_hours: "yes",
  },
  {
    id: 5,
    name: "shaving",
    images: "./assets/images/Services/shaving.png",
    services: "true",
    opening_hours: "yes",
  },
  {
    id: 6,
    name: "spa",
    images: "./assets/images/Services/spa.png",
    services: "true",
    opening_hours: "yes",
  },
];

export const BookingData = [
  {
    id: 1,
    name: "Liam Salon",
    services: ["Hair Cut", "Shaving"],
    opening_hours: "yes",
    booking_date: "10/07/2020",
    booking_status: 1,
  },
  {
    id: 2,
    name: "Noah Salon",
    services: ["Hair Style", "Makeup", "Spa", "Hair Color"],
    opening_hours: "yes",
    booking_date: "10/07/2020",
    booking_status: 0,
  },
  {
    id: 3,
    name: "William Salon",
    services: ["Hair Cut", "Hair Color"],
    opening_hours: "yes",
    booking_date: "10/07/2020",
    booking_status: 1,
  },
  {
    id: 4,
    name: "James Salon",
    services: ["Hair Style", "Makeup", "Spa"],
    opening_hours: "yes",
    booking_date: "10/07/2020",
    booking_status: 1,
  },
  {
    id: 5,
    name: "Oliver Salon",
    services: ["Hair Cut", "Shaving", "Spa", "Hair Color"],
    opening_hours: "yes",
    booking_date: "10/07/2020",
    booking_status: 0,
  },
  {
    id: 6,
    name: "Benjamin Salon",
    services: ["Hair Style", "Makeup", "Hair Color"],
    opening_hours: "yes",
    booking_date: "10/07/2020",
    booking_status: 1,
  },
  {
    id: 7,
    name: "Elijah Salon",
    services: ["Hair Cut", "Spa", "Hair Color"],
    opening_hours: "yes",
    booking_date: "10/07/2020",
    booking_status: 1,
  },
  {
    id: 8,
    name: "Lucas Salon",
    services: ["Hair Style", "Makeup", "Spa", "Hair Color"],
    opening_hours: "yes",
    booking_date: "10/07/2020",
    booking_status: 0,
  },

  {
    id: 12,
    name: "Sophia Salon",
    services: ["Hair Cut", "Spa", "Hair Color"],
    opening_hours: "yes",
    booking_date: "10/07/2020",
    booking_status: 1,
  },
  {
    id: 13,
    name: "Amelia Salon",
    services: ["Hair Cut", "Shaving", "Hair Style", "Makeup"],
    opening_hours: "yes",
    booking_date: "10/07/2020",
    booking_status: 0,
  },
];
