export default {
  GLOBAL: {
    TITLE: "Hair Force Uno",
    ACTION_DELETE: "Delete",
    ACTION_EDIT: "Edit",
    BUTTON_SAVE_AND_CLOSE: "Save and Close",
    BUTTON_SAVE_AND_SUMIT: "Save and Submit",
    BUTTON_CANCEL: "Cancel",
    BUTTON_SUBMIT: "Submit",
    BUTTON_EDIT: "Edit",
    THIS_FIELD_IS_MANDATORY: "This field is mandatory",
    SUCCESS: "SUCCESS",
    INFORMATION: "INFORMATION",
    ERROR: "ERROR",
    YES: "Yes",
    NO: "No",
    OK: "OK",
    BUTTON_SELECT: "Select",
    ACTIVE: "Verified",
    INACTIVE: "Un-Verified",
    ACCEPT: "Accept",
    REJECT: "Reject",
    PENDING: "Pending",
    COMPLETE: "Complete",
  },
  REGEX_PATTERN: {
    NUMBER: /^[0-9][0-9]*([.][0-9]{2}|)$/,
  },
  COMPONENTS: {
    UPLOAD_FILE: {
      ALLOWED_FILE_TYPES: "File types allowed,",
      UPLOAD: "Upload",
      UPLOAD_FILE: "Select File Here",
    },
  },
  SIDEBAR: {
    DASHBORD: "dashboard",
    CONSUMER: "Consumer",
    SERVICE_PROVIDER: "service provider",
    BOOKING: "bookings",
    TRANSACTION: "Transaction",
    APPOINTMENTS: "appointments",
    SERVICES: "services",
    ABOUT_US: "about us",
    TERM_AND_CONDITION: "terms & conditions",
    PRIVACYPOLICY:'privacy policy',
    CONTACT_LIST: "contact list",
  },
  LOGIN: {
    REGEX_OF_PASSWORD: /^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@$!%*#?&]).{8,32}$/,
    REGEX_OF_PASSWORD_NUMBER: /^(?=.*[0-9])/,
    REGEX_OF_PASSWORD_UPPERCASE: /^(?=.*[A-Z])/,
    REGEX_OF_PASSWORD_LOVERCASE: /^(?=.*[a-z])/,
    REGEX_OF_PASSWORD_SPECIAL: /^(?=.*[@$!%*#?&])/,
  },
  TABLE_LABELS: {
    BACK_BTN: "Back",
    CONSUMER_NAME: "Consumer Name",
    SERVICE_PROVIDER_NAME: "Service Provider",
    EMAIL: "Email *",
    HOUR_RATE: "Hour Rate *",
    PINCODE: "Zipcode *",
    ADDRESS: "Address *",
    CITY: "city *",
    STATE: "state *",
    COUNTRY: "country *",
    SERVICES: "Services",
    ABOUT: "About *",
    DATE: "Date *",
    TIME: "Time *",
    SUBMIT: "Submit",
    UPDATE: "Update",
    NO_DATA_FOUND: "NO DATA FOUND",
  },
  DASHBOARD: {
    TITLE: "Dashboard",
    CONSUMER: "Consumer",
    SERVICE_PROVIDER: "SERVICE PROVIDER",
    BOOKING: "Booking",
  },
  SERVICE_PROVIDER: {
    TITLE: "HairforceUno Service Providers",
    TABLE: {
      COL1: "Name",
      COL2: "Email",
      COL3: "Address",
      COL4: "Rate Hourly",
      // COL5: "", //Email Verified
      COL6: "Rating",
      COL7: "", //Account Verified
    },
    ADD_BTN: "Create New Service Provider",
    ADD_SERVICE_PROVIDER: {
      TITLE: "Add Service Provider",
    },
    EDIT_SERVICE_PROVIDER: { TITLE: "Edit Service Provider" },
  },
  CONSUMER: {
    TITLE: "HairforceUno Consumers",
    TABLE: {
      COL1: "Name",
      COL2: "Email",
      COL3: "Address",
      COL4: "Pincode",
      COL5: "", // Email Verified
      COL6: "No. of Bookings",
    },
    ADD_BTN: "Create New Consumer",
    ADD_CONSUMER: {
      TITLE: "Add Consumer",
    },
    EDIT_CONSUMER: { TITLE: "Edit Consumer" },
  },
  BOOKING: {
    TITLE: "HairforceUno Bookings",
    TABLE: {
      COL1: "Service provider",
      COL2: "Consumer",
      COL3: "Services",
      COL4: "Date",
      COL5: "Status",
    },
    ACCEPT: "Accepted",
    REJECT: "Rejected",
    PENDING: "Pending",
    ADD_BTN: "Create New Booking",
    ADD_BOOKING: {
      TITLE: "Add Booking",
    },
    EDIT_BOOKING: { TITLE: "View Details of Booking" },
  },
  TRANSACTION: {
    TITLE: "HairforceUno Transactions",
    TABLE: {
      COL1: "Service provider",
      COL2: "Consumer",
      COL3: "Date",
      COL4: "Total Charge",
      COL5: "Stripe Charge",
      COL6: "NET Total",
      COL7: "Admin Charge",
      COL8: "Service Provider Charge",
    },
    ACCEPT: "Accepted",
    REJECT: "Rejected",
    PENDING: "Pending",
    ADD_BTN: "Create New Booking",
    ADD_BOOKING: {
      TITLE: "Add Booking",
    },
    EDIT_BOOKING: { TITLE: "View Details of Booking" },
  },
  APPOINTMENTS: {
    TABLE: {
      COL1: "Service provider",
      COL2: "Consumer",
      COL3: "Services",
      COL4: "Date",
      COL5: "Status",
    },
    ACCEPT: "Accepted",
    REJECT: "Rejected",
    PENDING: "Pending",
    ADD_BTN: "Add",
    ADD_APPOINTMENT: {
      TITLE: "Add Appointment",
    },
    EDIT_APPOINTMENT: { TITLE: "Edit Appointment" },
  },
  CONTACT_LIST: {
    TABLE: {
      COL1: "Name",
      COL2: "Email",
      COL3: "Role",
      COL4: "Title",
      COL5: "DESCRIPTION",
    },
    ADD_BTN: "Add",
    ADD_CONTACT: {
      TITLE: "Add Contact",
    },
    EDIT_CONTACT: { TITLE: "Edit contact" },
  },
  SERVICES: {
    TITLE: "HairforceUno Services",
    TABLE: {
      COL1: "Icon",
      COL2: "Service Name",
      COL3: "status",
      COL4: "Action",
    },
    ADD_BTN: "Create New Service",
    ADD_SERVICE: {
      TITLE: "Add Service",
    },
    EDIT_SERVICE: { TITLE: "Edit Service" },
  },
  TERMS_AND_CONDITIONS: {
    TITLE: "Terms and Conditions",
  },
  PRIVACYPOLICY: {
    TITLE: "Privacy Policy",
  },
  ABOUT_US: {
    TITLE: "About Us",
  },
};
